<?php
/**
 * @file
 * Drupal hooks for the hosting_platform_git module.
 */

function hosting_platform_git_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'platform_node_form') {
    $platform_node_form = new HostingPlatformGitForm($form, $form_state);
    $platform_node_form->alter();
  }
}

/**
 * Implements hook_node_submit().
 */
function hosting_platform_git_node_submit($node, $form, &$form_state) {
  if ($node->type == 'platform') {
    $platform_node_form = new HostingPlatformGitForm($form, $form_state, $node);
    $platform_node_form->nodeSubmit();
  }
}

/**
 * Implements hook_field_attach_submit().
 */
function hosting_platform_git_field_attach_submit($entity_type, $entity, $form, &$form_state) {
  if ($entity_type == 'node' && $entity->type == 'platform') {
    $platform_node_form = new HostingPlatformGitForm($form, $form_state, $entity);
    $platform_node_form->fieldAttachSubmit();
  }
}

/**
 * Implements hook_node_view().
 */
function hosting_platform_git_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'platform') {
    $platform = new HostingPlatformGitNode($node);
    $platform->nodeView();
  }
}

/**
 * Implements hook_platform_deploy_strategies().
 */
function hosting_platform_git_platform_deploy_strategies() {
  return ['platform_git' => t('Deploy from Git repository')];
}


